### ISSUE TITLE
Extension does not seem to work with Firefox 84 (Warning processing windowTypes: This property is deprecated)

### ISSUE THREAD

**Issue by fad1** [mikl/add-to-omnifocus-webextension#6]
![image](https://user-images.githubusercontent.com/34130556/102448272-cb99d980-3fff-11eb-86ee-9747c8ce602a.png)

**Comment by austincloudguru** [comment]
@mikl can we get this merged?

**Comment by mikl** [comment]
There’s a new release, v1.1.1, pending review by Mozilla, that should help this.

**Comment by austincloudguru** [comment]
> There’s a new release, v1.1.1, pending review by Mozilla, that should help this.

Thanks!
